# Generated by Django 4.0.6 on 2022-08-04 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_board_app', '0002_alter_task_performer_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timezone',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('In progress', 'In progress'), ('In QA', 'In QA'), ('Ready', 'Ready'), ('Done', 'Done')], default='New', max_length=12),
        ),
    ]
