# Generated by Django 4.0.6 on 2022-08-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_board_app', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In progress'), (3, 'In QA'), (4, 'Ready'), (5, 'Done')], default=1),
        ),
    ]
