# Generated by Django 4.0.6 on 2022-08-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_board_app', '0005_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='timezone',
            new_name='time',
        ),
    ]
