# Generated by Django 4.0.6 on 2022-08-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_board_app', '0006_rename_timezone_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
    ]
