# Generated by Django 4.0.6 on 2022-08-18 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_board_app', '0007_remove_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 24, 14, 51374, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
